name: Deploy application to Cpanel
on:
  push:
     branches:
       - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Build Project
      run: |
        npm install
        npm run build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp.serverbyt.in
        username: dev@stss.in
        password: ${{ secrets.password }}
        server-dir: dem/
        local-dir: build/
        exclude: |
         admin/**